### ISSUE TITLE
Exception occur when select budget on GUI

### ISSUE THREAD

**Issue by yunjun199321** [CS2103-AY1819S2-W17-4/main#119]
1. set budget.
2. select budget on GUI

Exception:
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: Index -1 out-of-bounds for length 2.

3. add budget again but change to last year
error:
Caused by: seedu.address.model.epiggy.exceptions.DuplicateBudgetException: Operation would result in duplicate budgets
	at seedu.address.model.epiggy.UniqueBudgetList.setBudgetList(UniqueBudgetList.java:152)
	at seedu.address.model.AddressBook.setBudgetList(AddressBook.java:85)
	at seedu.address.model.AddressBook.resetData(AddressBook.java:104)
@tehwenyi

**Comment by tehwenyi** [comment]
Fixed in #121 by Minh
