### ISSUE TITLE
App launch fail

### ISSUE THREAD

**Issue by rahulb99** [CS2103-AY1819S2-W17-4/main#52]
I just tried launching the application today from `MainApp` but it shows the following error -
 `INFO: Starting UI...
Mar 11, 2019 8:53:38 PM seedu.address.ui.UiManager start
SEVERE: null
java.lang.NullPointerException
	at seedu.address.ui.HelpWindow.<init>(HelpWindow.java:31)
	at seedu.address.ui.HelpWindow.<init>(HelpWindow.java:39)
	at seedu.address.ui.MainWindow.<init>(MainWindow.java:73)
	at seedu.address.ui.UiManager.start(UiManager.java:41)
	at seedu.address.MainApp.start(MainApp.java:172)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
...`

**Comment by yunjun199321** [comment]
Try to pull upstream master again. This bug does not exist in my local project. My local project is up-to-date.
